--
--
-- Name: odts; Type: SCHEMA; Schema: -; Owner: odts_admin
--
CREATE SCHEMA odts;
--
--
ALTER SCHEMA odts OWNER TO odts_admin;
--
set search_path = odts;
--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--
COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
--
-- Name: code_reference; Type: TABLE; Schema: odts; Owner: ajitverma
--
CREATE TABLE odts.code_reference (
    code_type VARCHAR(50),
    code_label VARCHAR(50),
    code VARCHAR(20) NOT NULL,
    code_desc VARCHAR(250),
    code_sort_order integer DEFAULT 0,
    created_by integer DEFAULT 0 NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
-- Name: code_reference code_reference_pkey; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.code_reference
    ADD CONSTRAINT code_reference_pkey PRIMARY KEY (code);
--
-- Name: dealer_orders; Type: TABLE; Schema: odts; Owner: odts_admin
--
CREATE TABLE odts.dealer_orders (
    order_id integer NOT NULL,
    dealer_id integer NOT NULL,
    order_date timestamp NOT NULL,
    order_status VARCHAR(255) NOT NULL,
    party_id integer,
    preferred_location_code VARCHAR(20),
    load_type_code VARCHAR(20),
    on_hold_reason text,
    on_hold_by integer,
    on_hold_by_role VARCHAR(255),
    order_executed_at TIMESTAMP,
    driver_name VARCHAR(255),
    driver_phone VARCHAR(20),
    vehicle_number VARCHAR(50),
    created_by integer DEFAULT 0 NOT NULL,
    created_at timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
    --to check
    --CONSTRAINT dealer_orders_order_quantity_check CHECK ((order_quantity > 0))
);
--
--
-- Name: TABLE dealer_orders; Type: COMMENT; Schema: odts; Owner: odts_admin
--
COMMENT ON TABLE odts.dealer_orders IS 'Transaction Entity';
--
-- Name: dealer_orders_order_id_seq; Type: SEQUENCE; Schema: odts; Owner: odts_admin
--
ALTER TABLE odts.dealer_orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.dealer_orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: dealer_orders dealer_orders_pkey; Type: CONSTRAINT; Schema: odts; Owner: odts_admin
--
ALTER TABLE ONLY odts.dealer_orders
    ADD CONSTRAINT dealer_orders_pkey PRIMARY KEY (order_id);
--
--TO CHECK
--UNIQUE ??
--
-- Name: dealer_party_master; Type: TABLE; Schema: odts; Owner: ajitverma
--
CREATE TABLE odts.dealer_party_master (
    party_id integer NOT NULL,
    dealer_id integer,
    party_code VARCHAR(255) NOT NULL,
    party_company_name VARCHAR(255),
    party_name VARCHAR(255),
    party_address text,
    party_phone VARCHAR(255),
    party_email VARCHAR(255),
    party_is_active_flag boolean DEFAULT true,
    created_by integer DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
-- Name: dealer_party_party_id_seq; Type: SEQUENCE; Schema: odts; Owner: ajitverma
--

ALTER TABLE odts.dealer_party_master ALTER COLUMN party_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.dealer_party_party_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: dealer_party dealer_party_pkey; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.dealer_party_master
    ADD CONSTRAINT dealer_party_pkey PRIMARY KEY (party_id);
--
-- Name: dealers; Type: TABLE; Schema: odts; Owner: ajitverma
--
CREATE TABLE odts.dealer_master (
    dealer_id integer NOT NULL,
    dealer_code VARCHAR(50) NOT NULL,
    dealer_name VARCHAR(255),
    dealer_company_name VARCHAR(255) NOT NULL,
    dealer_phone VARCHAR(20),
    dealer_email VARCHAR(255),
    dealer_address text,
    dealer_daily_limit integer,
    dealer_monthly_target integer,
    dealer_is_active_flag boolean DEFAULT true NOT NULL,
    created_by integer DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
-- Name: dealers_dealer_id_seq; Type: SEQUENCE; Schema: odts; Owner: ajitverma
--
ALTER TABLE odts.dealer_master ALTER COLUMN dealer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.dealers_dealer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: dealers dealers_dealer_code_key; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.dealer_master
    ADD CONSTRAINT dealers_dealer_code_key UNIQUE (dealer_code);
--
-- Name: dealers dealers_pkey; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.dealer_master
    ADD CONSTRAINT dealers_pkey PRIMARY KEY (dealer_id);
--
-- Name: order_dispatch; Type: TABLE; Schema: odts; Owner: odts_admin
--
CREATE TABLE odts.order_dispatch (
    dispatch_id integer NOT NULL,
    order_id integer NOT NULL,
    created_by integer DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
-- Name: TABLE order_dispatch; Type: COMMENT; Schema: odts; Owner: odts_admin
--

COMMENT ON TABLE odts.order_dispatch IS 'Transaction Entity';
--
-- Name: order_dispatch_dispatch_id_seq; Type: SEQUENCE; Schema: odts; Owner: odts_admin
--
ALTER TABLE odts.order_dispatch ALTER COLUMN dispatch_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.order_dispatch_dispatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: order_dispatch order_dispatch_pkey; Type: CONSTRAINT; Schema: odts; Owner: odts_admin
--
ALTER TABLE ONLY odts.order_dispatch
    ADD CONSTRAINT order_dispatch_pkey PRIMARY KEY (dispatch_id);
--
create table odts.order_dispatch_items
(
dispatch_items_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
dispatch_id INTEGER NOT NULL,
dispatch_product_id INTEGER,
dispatch_warehouse_id INTEGER,
dispatch_bags INTEGER,
dispatch_quantity NUMERIC(10,3),
dispatch_date TIMESTAMP,
dispatch_vehicle_number VARCHAR(255),
dispatch_driver_name VARCHAR(255),
dispatch_driver_phone VARCHAR(255),
dispatch_bilty_number VARCHAR(255),
dispatch_receipt_image_url TEXT,
dispatch_receipt_image_type VARCHAR(255),
dispatch_receipt_image_orig_size INTEGER,
dispatch_receipt_image_comp_size INTEGER,
dispatch_notes VARCHAR(1000),
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_by INTEGER NOT NULL DEFAULT 0,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY (dispatch_items_id)
);
--
-- Name: products; Type: TABLE; Schema: odts; Owner: odts_admin
--
CREATE TABLE odts.product_master (
    product_id integer NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_desc text,
    product_is_active_flag boolean NOT NULL,
    created_by integer DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: odts; Owner: odts_admin
--
ALTER TABLE odts.product_master ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: odts; Owner: odts_admin
--
ALTER TABLE ONLY odts.product_master
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);
--
-- Name: products products_product_name_key; Type: CONSTRAINT; Schema: odts; Owner: odts_admin
--
ALTER TABLE ONLY odts.product_master
    ADD CONSTRAINT products_product_name_key UNIQUE (product_name);
--
-- Name: user_login_audit; Type: TABLE; Schema: odts; Owner: ajitverma
--
CREATE TABLE odts.user_login_audit (
    login_audit_id integer NOT NULL,
    login_user_id integer NOT NULL,
    login_method VARCHAR(255),
    login_status VARCHAR(255),
    login_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    logout_at TIMESTAMP,
    login_ip_address VARCHAR(255),
    login_is_active boolean DEFAULT false
);
--
--
-- Name: user_login_audit_login_audit_id_seq; Type: SEQUENCE; Schema: odts; Owner: ajitverma
--
ALTER TABLE odts.user_login_audit 
ALTER COLUMN login_audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.user_login_audit_login_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: user_roles; Type: TABLE; Schema: odts; Owner: odts_admin
--
CREATE TABLE odts.user_roles_master
 (
    role_id integer NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    role_desc text,
    created_by integer DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
--
-- Name: TABLE user_roles; Type: COMMENT; Schema: odts; Owner: odts_admin
--
COMMENT ON TABLE odts.user_roles_master IS 'user roles';
--
-- Name: user_roles_role_id_seq; Type: SEQUENCE; Schema: odts; Owner: odts_admin
--
ALTER TABLE odts.user_roles_master ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.user_roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: odts; Owner: odts_admin
--
ALTER TABLE ONLY odts.user_roles_master
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id);
--
-- Name: user_roles user_roles_role_name_key; Type: CONSTRAINT; Schema: odts; Owner: odts_admin
--
ALTER TABLE ONLY odts.user_roles_master
    ADD CONSTRAINT user_roles_role_name_key UNIQUE (role_name);
--
/*
ALTER TABLE odts.user_roles_master ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    drop SEQUENCE odts.user_roles_role_id_seq
);
*/
--
-- Name: users; Type: TABLE; Schema: odts; Owner: ajitverma
--
--
CREATE TABLE odts.user_master (
    user_id integer NOT NULL,
    user_role_id integer NOT NULL,
    dealer_id integer,
    user_login_name VARCHAR(50) NOT NULL,
    password_hash text NOT NULL,
    user_name VARCHAR(255),
    user_phone VARCHAR(20),
    user_email VARCHAR(255),
    user_is_active_flag boolean DEFAULT true NOT NULL,
    user_is_locked_flag boolean DEFAULT false NOT NULL,
    user_warehouse_id INTEGER, 
    created_by integer DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by integer DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--
--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: odts; Owner: ajitverma
--
ALTER TABLE odts.user_master ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME odts.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.user_master
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);
--
-- Name: users users_user_phone_key; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.user_master
    ADD CONSTRAINT users_user_phone_key UNIQUE (user_phone);
--
--
--
-- Name: user_login_audit user_login_audit_pkey; Type: CONSTRAINT; Schema: odts; Owner: ajitverma
--
ALTER TABLE ONLY odts.user_login_audit
    ADD CONSTRAINT user_login_audit_pkey PRIMARY KEY (login_audit_id);
--
--
-- Name: TABLE users; Type: ACL; Schema: odts; Owner: ajitverma
--
GRANT ALL ON TABLE odts.user_master TO odts_admin;
--
CREATE TABLE odts.dealer_order_items (
  item_id        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  order_id       INTEGER NOT NULL,
  product_id     INTEGER NOT NULL,
  order_bags     INTEGER,
  order_quantity NUMERIC(10,3) NOT NULL,
  --created_by     INTEGER NOT NULL DEFAULT 0,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  --updated_by     INTEGER NOT NULL DEFAULT 0,
  --updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY(item_id)
);
--
--drop table odts.warehouse_master cascade;
--
CREATE TABLE IF NOT EXISTS odts.warehouse_master (
	"warehouse_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"warehouse_code" VARCHAR(255) NOT NULL,
	"warehouse_name" VARCHAR(255) NOT NULL,
	"warehouse_type" VARCHAR(255) NOT NULL,
	"warehouse_ui_label" VARCHAR(255),
	"warehouse_ui_order" INTEGER,
	"created_by" INTEGER NOT NULL DEFAULT 0,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_by" INTEGER NOT NULL DEFAULT 0,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY("warehouse_id")
);
--
create table IF NOT EXISTS odts.warehouse_stock
(
warehouse_stock_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
warehouse_id INTEGER NOT NULL,
warehouse_stock_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
warehouse_vehicle_number VARCHAR(255),
warehouse_driver_name VARCHAR(255),
warehouse_driver_phone VARCHAR(255),
warehouse_bilty_number VARCHAR(255),
warehouse_receipt_image_url TEXT,
warehouse_receipt_image_type VARCHAR(255),
warehouse_receipt_image_orig_size INTEGER,
warehouse_receipt_image_comp_size INTEGER,
warehouse_stock_notes VARCHAR(1000),
is_dispatch_out BOOLEAN,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_by INTEGER NOT NULL DEFAULT 0,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY (warehouse_stock_id)
);
--
create table IF NOT EXISTS odts.warehouse_stock_items
(
warehouse_stock_item_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
warehouse_stock_id INTEGER NOT NULL,
warehouse_product_id INTEGER NOT NULL,
warehouse_product_qty INTEGER NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_by INTEGER NOT NULL DEFAULT 0,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by INTEGER NOT NULL DEFAULT 0,
PRIMARY KEY (warehouse_stock_item_id)
);
--
create table IF NOT EXISTS odts.warehouse_inventory
(
warehouse_inventory_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
warehouse_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
current_qty INTEGER NOT NULL,
last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (warehouse_inventory_id)
);
--
ALTER TABLE odts.warehouse_inventory
ADD CONSTRAINT uk_warehouse_inventory_wh_prod
UNIQUE (warehouse_id, product_id);
--
-- Create WhatsApp message templates table
CREATE TABLE IF NOT EXISTS odts.whatsapp_message_templates (
  template_id SERIAL PRIMARY KEY,
  template_name VARCHAR(255) NOT NULL UNIQUE,
  message_body TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_by INT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
  --to check below
 -- FOREIGN KEY (created_by) REFERENCES odts.user_master(user_id)
);
--
-- Create WhatsApp message logs table
CREATE TABLE IF NOT EXISTS odts.whatsapp_message_logs (
  message_id SERIAL PRIMARY KEY,
  dealer_id INT NOT NULL,
  phone_number VARCHAR(50) NOT NULL,
  template_id INT,
  message_sent TEXT,
  status VARCHAR(50) NOT NULL,
  message_sid VARCHAR(255),
  error_message TEXT,
  sent_at TIMESTAMP DEFAULT NOW(),
  sent_by INT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
   --to check below
  --FOREIGN KEY (dealer_id) REFERENCES odts.dealer_master(dealer_id),
  --FOREIGN KEY (template_id) REFERENCES odts.whatsapp_message_templates(template_id) ON DELETE SET NULL,
  --FOREIGN KEY (sent_by) REFERENCES odts.user_master(user_id)
);
--
--
CREATE TABLE odts.dealer_order_items (
  item_id        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  order_id       INTEGER NOT NULL REFERENCES odts.dealer_orders(order_id) ON DELETE CASCADE,
  product_id     INTEGER NOT NULL,
  order_bags     INTEGER,
  order_quantity NUMERIC(10,3) NOT NULL,
  --created_by     INTEGER NOT NULL DEFAULT 0,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  --updated_by     INTEGER NOT NULL DEFAULT 0,
  --updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY (item_id)
);
--
select * from odts.dealer_order_items;
--change item_id to order_item_id , pk
--
--
-- Step 1: Drop existing triggers
DROP TRIGGER IF EXISTS trg_warehouse_dispatch_out ON odts.order_dispatch_items CASCADE;
DROP TRIGGER IF EXISTS fn_update_inventory_dispatch_out ON odts.order_dispatch_items CASCADE;

-- Step 2: Drop existing functions
DROP FUNCTION IF EXISTS public.fn_update_inventory_dispatch_out() CASCADE;
DROP FUNCTION IF EXISTS odts.fn_update_inventory_dispatch_out() CASCADE;
--
-- recreate function
CREATE OR REPLACE FUNCTION odts.fn_update_inventory_dispatch_out()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE odts.warehouse_inventory
  SET
    current_qty = current_qty - NEW.dispatch_bags,
    last_updated = NOW()
  WHERE warehouse_id = NEW.dispatch_warehouse_id
    AND product_id = NEW.dispatch_product_id;
  
  RETURN NEW;
END;
$function$;
--
-- recreate the function
CREATE OR REPLACE FUNCTION odts.fn_update_inventory_stock_in()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO odts.warehouse_inventory (warehouse_id, product_id, current_qty, last_updated)
  SELECT 
    ws.warehouse_id,
    NEW.warehouse_product_id,
    NEW.warehouse_product_qty,
    NOW()
  FROM odts.warehouse_stock ws
  WHERE ws.warehouse_stock_id = NEW.warehouse_stock_id
  ON CONFLICT (warehouse_id, product_id)
  DO UPDATE SET
    current_qty = warehouse_inventory.current_qty + NEW.warehouse_product_qty,
    last_updated = NOW();
  
  RETURN NEW;
END;
$function$;
--
-- recreate the trigger
CREATE TRIGGER trg_warehouse_stock_in
AFTER INSERT ON odts.warehouse_stock_items
FOR EACH ROW
EXECUTE FUNCTION odts.fn_update_inventory_stock_in();
--
-- recreate the trigger
CREATE TRIGGER trg_warehouse_dispatch_out
AFTER INSERT ON odts.order_dispatch_items
FOR EACH ROW
EXECUTE FUNCTION odts.fn_update_inventory_dispatch_out();
--
-- to Verify the function and trigger
SELECT pg_get_functiondef(oid) 
FROM pg_proc 
WHERE proname = 'fn_update_inventory_dispatch_out' 
AND pronamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'odts');
--
-- to get trigger information
--
SELECT trigger_name, trigger_schema, event_manipulation 
FROM information_schema.triggers 
WHERE event_object_table = 'order_dispatch_items' 
AND trigger_schema = 'odts';
--
-- to get column name, data type for columns
--
SELECT
    column_name,
    data_type,
    character_maximum_length,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'code_reference'
ORDER BY ordinal_position;
--